### ISSUE TITLE
我看之前已经启用了mysqli的支持，好想没有完成

### ISSUE THREAD

**Issue by rongzedong** [zhengyong100/ji#5]
这是咋回事呢，44c27b9  on 15 Oct
@zhengyong100 zhengyong100 修改成mysqli_connect兼容支持php5+数据库连接。

**Comment by rongzedong** [comment]
期待下一步考虑引入正规记账的分类帐，并且可以生成报表

**Comment by zhengyong100** [comment]
是啊，之前没弄好，就在12月21号我又更新了，然后才知道你在12号那天也更新了，没去注意。。另外，那个导出不是excel报表吗？ 对了，SLT2和rongzedong 你两个号啊。  ：） 谢谢修改哈

**Comment by rongzedong** [comment]
> SLT2

SLT2 不是我， rongzedong 是另外一个 人。 哈哈
